version: '3.1'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:1234@db:3306/fitlifehub
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: fitlifehub
      MARIADB_USER: root
      MARIADB_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
